---
title: "NHS Borders Cancer Incidence Report"
author: "Sarina Singh Khaira"
date: "02/02/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction & Methodology

This analysis reports on the incidence of cancer within the NHS Borders health board. Data includes cancer admission by cancer site and gender for the years 1994 - 2018 and can be found [here](https://www.opendata.nhs.scot/dataset/annual-cancer-incidence). 

Each cancer site is classified according to the ICD10 code, an alpha numeric code which corresponds to each type of cancer and where it is found in the body. 

This analysis focuses on the total number of new cancer registrations, the crude rate per population as well as the standardised incidence ratio of each cancer type. The EASR and WASR have not been included as this report focuses solely on admissions within the Borders health board, and is not to be used to compare cancer rates with other nations. 

##### Standardised Incidence Ratio (SIR)
The standardised incidence ratio (SIR) is used to determine if the occurence of a certain type of cancer is higher or lower than expected in a relatively small population, given the population and age distribution of the community. 

If the SIR is greater than 100, it indicates that the cancer rate is higher than expected in that particular population. If the SIR is lower than 100, the cancer rate is lower than expected,

Care must be taken to interpret the SIR, as often the confidence limits can have a very large range. If the lower 95% CI is less than 100, and the upper is more than 100, it is possible that the true SIR does not deviate from 100 (is as expected.)

# Findings
## Summary Statistics
 * ow many admissions per year?
 * increase since 1992?
 * cancer with the most number of admissions?
 * in 2018, how many men and how many women?
## Top 10 types of cancer per gender
### If they are increasing or decreasing with time
## Cancers with a high SIR - higher than expected rates